### PR TITLE
Update TPSubs.php

### PR DESCRIPTION
**Pull request by Underdog-01**
Replace document.write with DOM nodes.
document.write is primarily used for testing during development and is not supposed to be used in production/stable packages.

I've never used Cloudflare libraries but after briefly looking at their source code, they appear to be libraries for Vanilla JavaScript.
This is why I decided to have the DOM insert the nodes as the first children of the HEAD tag.

Signed-off-by: Chen Zhen <github.underdog@gmail.com>

### CODE REVIEW

**Comment by tinoest** [comment]
Can you put brackets on the last else so it’s consistent with the else if and I’ll merge this in. 

You don’t need to sign off for this project btw.

**Comment by tinoest** [comment]
Thanks

**Comment by Underdog-01** [comment]
It looks like my editor also cleaned up all the odd spaces at the end of lines.
Your editor should have a "trim trailing space" option which will clean up a file like that.

I tested this for errors but did not actually test its function to see if the node fires as intended, 
There are some questions I would like to ask:

Is the CloudFlare library strictly for IE (not Edge) and for which version(s)?
Does this handle a drag & drop feature that some older versions of IE needed?
What part of the TP admin would use this so I can test it all out?

Is JQuery for SMF 2.0 loaded prior to this? If it is then the last 3 conditions can be written as one using JQuery.

**Comment by tinoest** [comment]
I noticed that, I use vim as my editor and forget to enable that sometimes. I’m not sure what @Bopske uses. 

Cloudflare is used for versions of IE prior to edge for drag and drop. On the html editor screen for articles. JQuery should be loaded by then. I don’t mind that or normal JavaScript. I think the code says which ones, if not I’ll get back to you.

To be honest it can probably be dropped now as no one should use them. It was added for @lurkalot way back when that feature was introduced.

**Comment by Underdog-01** [comment]
I have come across people within the last year that still use Windows 7 & IE although it is rare.
At some point tonight or tomorrow I will give it a test and if there are any problems I will update with an edit that works as intended.

**Comment by Bopske** [comment]
I am not a programmer as such, so I am not into the more hardcore editors... I do my tinkering on Notepad++, but the trailing space thing is interesting: I’ll see if there is an option / plug-in for that

**Comment by Bopske** [comment]
Found it, default macro under Alt+Shift+S, never knew that before...

**Pull request merged**
