### PR TITLE
Update dlmanager 'useredit'

### PR DESCRIPTION
**Pull request by Bopske**
I found that the useredit function for the DL manager was not updated to the 2.1  layout. While doing so I found that the Wysiwyg editor is non-functional on that screen. The HTML editor is absent, and the BBC editor actually gives an error.

In 2.1 it throws error: 8: Undefined index: editor_id
https://test2.fjr-club.nl/index.php?action=tpmod;dl=useredit26
/home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPdlmanager.template.php (Line 845)

In 2.0 it breaks down with this error: Call to undefined function template_control_richedit()

This only happens in the screen that a user (non admin) uses to edit his own download...

Tino, please have a look at it if you can: since you were able ton fix the editor in all other places...

### CODE REVIEW

**Comment by tinoest** [comment]
I can't see anywhere in the code where we access useredit for downloads, just adminitem?

**Comment by Bopske** [comment]
I am not sure. There is a check if user that edits is admin. If not he is redirected to useredit

**Comment by Bopske** [comment]
Is it not here in TPdlmanager:
line 2767

		// if we came from useredit screen..
		if(isset($_POST['dl_useredit']))
		   redirectexit('action=tpmod;dl=useredit'.$_POST['dl_useredit']);

		if(!empty($newgo))
			$go = $newgo;
		// guess not, admin screen then
		if($go == 1)
			redirectexit('action=tpmod;dl=adminsettings');
		elseif($go == 2)
			redirectexit('action=tpmod;dl=adminitem'.$myid);
		elseif($go == 3)
			redirectexit('action=tpmod;dl=admineditcat'.$myid);
		elseif($go == 4)
			redirectexit('action=tpmod;dl=admincat'.$myid);

**Comment by tinoest** [comment]
Looks like it, not sure why there are so many ways to edit the same thing. I’ll rationalise in TP2 and make it only one. 

I’ll look at fixing it in TP1

**Comment by Bopske** [comment]
It is in TPdlmanager.php line 3397

// edit screen for regular users
function TPortalDLUser($item)

Which is called from TPdlmanager_int on line 45

		// see if its admin section
		if(substr($context['TPortal']['dlsub'], 0, 5) == 'admin' || $context['TPortal']['dlsub']=='submission')
			TPortalDLAdmin();
		elseif(substr($context['TPortal']['dlsub'], 0, 8) == 'useredit')
			TPortalDLUser(substr($context['TPortal']['dlsub'], 8));
		else
			TPortalDLManager();

**Comment by Bopske** [comment]
Agree, it is bit of a spaghetti nightmare if you dig into it. I think fixing the editor in this extra case should be relatively simple for 1.6.3 

How are you coming along with the 2.0 cleanup? Have not looked into the code yet, but if you are seeing light at the end of the tunnel I may see if I can make sense of the new codebase...

**Comment by tinoest** [comment]
I’ve done the basic for shout, split out search, rewrote the portal article stuff. Need to do downloads and completely clear out modules. 

Have concerns about the conversion from TinyPortal 1 to 2 as I moved all the directories around, I might change it so you can specify where the downloads/images/etc are stored.

**Pull request merged**
