### PR TITLE
PR944

### PR DESCRIPTION
**Pull request by tinoest**
Replaces #944

### CODE REVIEW

**Comment by tinoest** [comment]
@Bopske please review and make sure it does what you would like and then commit. 

I don't have any better images, but I am not sure what changed with these but they don't look very good anymore. 

Screenshot 2023-01-07 at 17 10 29

**Comment by Bopske** [comment]
Looking good. Just still have the issue that I was having before: when the Position for new messages is set to "Bottom" the refresh should scroll the shoutbox the the bottom, when it is set to "Top" it should scroll to top.

That was what I mentioned in my PR:
" There is one item I have not been able to fix yet: the ajax refresh still messes up the sort order and scrollbar position. Even with trying the solutions mentioned here..."

 Any idea how to fix that? It now always scrolls to the bottom...

By the way: I increased these images in size (as requested) and they do not have sufficient quality. I will try to find something better

**Comment by tinoest** [comment]
That didn’t for me, it scrolled to the top or bottom as I’d expect. I’d had to clear the js cache after the update to force it through

**Comment by Bopske** [comment]
Hmmm, just tested in an incognito window: as a quest the scroll works correcty, but lgged in as admin it does not?

**Comment by tinoest** [comment]
> Hmmm, just tested in an incognito window: as a quest the scroll works correcty, but lgged in as admin it does not?

Try it with my latest push, I moved it to another location where it should work better.

**Comment by Bopske** [comment]
Wait: it does work It just seems the sort order itself is reversed...!

I will merge this PR and then start some more testing...

**Comment by Bopske** [comment]
Latest code is working fine!

**Pull request merged**
