### PR TITLE
Revert bbc parsing for smf 2.0

### PR DESCRIPTION
**Pull request by Bopske**

### CODE REVIEW

**Comment by Bopske** [comment]
Tested this change, and it works, did I miss anything? I don't think I have to declare TP_SMF21 in the code bit it 'feels'  wrong...

**Comment by tinoest** [comment]
> Tested this change, and it works, did I miss anything? I don't think I have to declare TP_SMF21 in the code bit it 'feels' wrong...

Why does it feel wrong?

You can use && instead of the double if statement. 

if(TP_SMF21 && ..

**Comment by Bopske** [comment]
Calling the variable without making it a gobal I mean. 

And yes I know I can use the && but I like this notation a bit better, since imo it is a bit clearer to strip it it again if we are dropping 2.0 support in future...

**Comment by tinoest** [comment]
It’s a constant which is a global really, I prefer them as you don’t need the global keyword.

**Pull request merged**
