### PR TITLE
Added an extra css for custom css

### PR DESCRIPTION
**Pull request by Bopske**
Solution for #364

### CODE REVIEW

**Comment by Bopske** [comment]
Tino, if you have time to review this?

I added an extra css (tp-custom.css) to use for 'own' css by site admins.
I was thinking that it would be ideal if there is a check upon install for existence of the file, and if it is found to NOT overwrite the custom.css

However I do not know what is the correct way to do that check, so atm I leave the custom.css in place upon uninstall, but it will be overwritten when installing again...
What do you think?

**Comment by tinoest** [comment]
I’ll review on Sunday if that’s ok?

**Comment by Bopske** [comment]
Sure, thanks.

Don't mind the extra commits on css and blockcode. They are unrelated, but can tag along...

**Comment by Bopske** [comment]
any change you can provide feedback on this tino?

**Pull request merged**
