### PR TITLE
Moved tp-images and Defaults for articles updated

### PR DESCRIPTION
**Pull request by Bopske**

### CODE REVIEW

**Comment by Bopske** [comment]
I have moved the tp-images folder back and updated the setting to the old standard folder /tp-images

The variable $context['TPortal']['image_upload_path'] is used where it was already implemented by you and I also updated some other locations (tplistimages to start). The download manager needs to be updated still, but to do it completely we also need a variable for dealing with $boardurl instead of $boarddir. 

Not sure if there is a simple trick to add a boardurl variable to $context that is derived from boarddir? 
Do you have a tip for me?

**Comment by tinoest** [comment]
Can you give me an example where you need boardurl? 

I would have a different variable called image_upload_url with that set myself. Or something similar.

**Comment by Bopske** [comment]
Just going out for dinner... if jou check TPlistimages.php there is at least one occurrence where boardurl is needed with tp-images url.
If you can get me started with the extra variable that would be great...

**Comment by Bopske** [comment]
Good example is line 121:
 
                   $imageUrl   = $boardurl.'/tp-images/thumbs/'.$im;

By the way: the same applies to the variable for the downloads: $context['TPortal']['download_upload_path']
There are also images placed in the sub-folder here, so when moving the downloads folder these images also need to be redirected, so another boardurl variable there..

For example; TPdlmanager.php

Line 2239.
$icon = $boardurl.'/tp-downloads/icons/'.$_POST['newdladmin_icon'];

**Comment by Bopske** [comment]
Merging this now so Lurk can do some testing too..

**Pull request merged**
