### PR TITLE
Shoutbox settings for ID and layout in Block

### PR DESCRIPTION
**Pull request by Bopske**
Tino,

I have added the shoutbox Block settings for Shoutbox ID as well as layout and height. 
The layout per block works, the admin function for Shoutbox ID selection works too. The only thing I cannot yet get to work is the block to use the Shoutbox_ID (stored in $block['var2'] ) instead of the $blockid in the shoutbox.

Not sure where this is set now: the shoutbox work differently from the other blocks.

Can you check how to change the shoutbox to use the Shoutbox_ID?

There are a few things left to do: 
1. I also see that when posting in a shoutbox block it seems to return to the default layout instead of keeping the block layout
2. When submitting the shout the text seems to stay in the entry box...

### CODE REVIEW

**Comment by tinoest** [comment]
I just created a PR against your repo with changes to pass the shoutbox_id through to the blocks.

**Comment by tinoest** [comment]
What’s outstanding on getting this merged?

**Comment by Bopske** [comment]
Open is:
1. The layout setting issue: on refresh it still uses the default forum setting and not the block layout
2. The shout on Enter function
3. The general settings for the shoutbox need to be removed from install.php

    'shoutbox_height' => '250',
    'shoutbox_layout' => '0',

**Comment by tinoest** [comment]
> Open is:
> 
> 1. The layout setting issue: on refresh it still uses the default forum setting and not the block layout

That works for me now. 

> 2. The shout on Enter function

Also works for me now. 

> 3. The general settings for the shoutbox need to be removed from install.php
>    'shoutbox_height' => '250',
>    'shoutbox_layout' => '0',

That’s an update to install.php?

**Comment by Bopske** [comment]
Let's merge it in then and I'll test the latest once more...

**Comment by Bopske** [comment]
Open is:

The layout setting issue: on refresh it still uses the default forum setting and not the block layout
That works for me now.

>> not for me
Hit refresh and I now get an empty shoutbox (since the forum setting is removed) and It rains errors:

Type of error: Undefined8: Undefined index:  https://test2.fjr-club.nl/index.php?action=tpshout;shout=fetch /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPShout.template.php (Line 426) |  
-- | --
@rjen Today at 22:13 62.194.61.141 af2cff86ca45738b67e5d552fcf764d0Backtrace information Type of error: Undefined8: Undefined index: shoutbox_layout https://test2.fjr-club.nl/index.php?action=tpshout;shout=fetch /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPShout.template.php (Line 361)

The shout on Enter function
Also works for me now.

>> Enter works indeed, it just does not clean the entry box 

The general settings for the shoutbox need to be removed from install.php
'shoutbox_height' => '250',
'shoutbox_layout' => '0',
That’s an update to install.php?

Yep, just added that to this PR

**Comment by tinoest** [comment]
Are you sure you have the latest js file?

**Comment by Bopske** [comment]
Yes

**Comment by tinoest** [comment]
> Yes

I just took your pr and it's not giving me any of these errors on a clean install.

**Comment by Bopske** [comment]
Try removing the shoutbox layout setting from tp_settings table

**Comment by tinoest** [comment]
> Try removing the shoutbox layout setting from tp_settings table

No rows found when I look for that setting

**Comment by Bopske** [comment]
No 'shoutbox_layout' => '0',?

I only removed it from install.php tonight! 
But like I said: merge it, and I will install it clean on a 2.1 RC3 test site

**Comment by tinoest** [comment]
> No 'shoutbox_layout' => '0',?
> 
> I only removed it from install.php tonight!
> But like I said: merge it, and I will install it clean on a 2.1 RC3 test site

Yeh I merged your changes in after you’d done them and tested on a clean install

**Pull request merged**
