### PR TITLE
Changes for lang option

### PR DESCRIPTION
**Pull request by tinoest**

### CODE REVIEW

**Comment by tinoest** [comment]
Is this any better?

**Comment by Bopske** [comment]
Not really...

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(FIND_IN_SET('tlang=english', access2))
ORDER BY pos,id ASC' at line 5
File: C:\xampp\htdocs\smf21\Sources\TPortal.php
Line: 1693

**Comment by tinoest** [comment]
I’ll look at it tomorrow when I can test on my MySQL install.

**Comment by tinoest** [comment]
Although I think I just missed the AND before the find in set?

**Comment by Bopske** [comment]
I am confused now. In the latest code you seem to determine acces2 multiple times: twice for MySQL and twice for others... ?

**Comment by tinoest** [comment]
I add to the string, you added the allpages one, I assume for a reason? So I just added to the string for the language stuff.

**Comment by Bopske** [comment]
The code in Tportal is only used for the front panel blocks: the rest of the code is in TPBlocks: that is used for all other panels. In the front panel there was no language visibility before: I ported some of the code from the section that is now in TPBlocks over. 

The allpages was there as well. Not sure why it is exactly there, but it seems needed...

**Comment by tinoest** [comment]
Well it 'should' work now.

**Comment by Bopske** [comment]
Yep, both front panel and other panels are working with the language visibility option now!

**Pull request merged**
