### PR TITLE
Merge latest Development into master 

### PR DESCRIPTION
**Pull request by tinoest**

### CODE REVIEW

**Comment by tinoest** [comment]
@Bopske @Underdog-01 I am not sure which one's are correct on the file conflicts for TPShout and the templates, can you have a look and resolve them?

**Comment by Bopske** [comment]
I am sorry, not sure how to resolve these... all I know is that development branche was OK: I tested it in the latest status. How did these conflicts start?

**Comment by tinoest** [comment]
> I am sorry, not sure how to resolve these... all I know is that development branche was OK: I tested it in the latest status. How did these conflicts start?

They started as there were changes made in the master which also made in the development with a merge between the two so git doesn't know which one is correct. 

The install.php one is mine and is a tab spacing difference. The others are all recent changes. I would guess that head is correct, but I honestly don't know.

**Comment by Bopske** [comment]
I understand what the technical cause of these conflicts would be, I am also sure I would be able to identify the correct code, I just do not have a clue how to resolve these conflicts. I am not an editor user, and work mostly in github desktop.

I am not even able to produce the details on the conflicts. I just see the list of affected files...

**Comment by tinoest** [comment]
You can check them out into GitHub desktop to resolve them. I think the instructions say how to do that.

**Pull request merged**
