### PR TITLE
TPListImages default to users language

### PR DESCRIPTION
**Pull request by tinoest**

### CODE REVIEW

**Comment by tinoest** [comment]
@ArjenWelling I think this will resolve the language issue?

**Comment by Bopske** [comment]
That works. Just not sure if it is not possible to use the default SMF way to determine the language?

**Comment by tinoest** [comment]
Not without changing the directory, they only expect the languages in the SMF location and you can’t change that. 

I can use template_include still mind

**Comment by Bopske** [comment]
It's not a big deal. Don't know what template_include would bring that's better...

**Pull request merged**
