### PR TITLE
Localize for SCEditor

### PR DESCRIPTION
**Pull request by dragomano**

### CODE REVIEW

**Review by tinoest — APPROVED** [review]

**Comment by Bopske** [comment]
seems to work on 2.1, but no change on 2.0?

**Comment by dragomano** [comment]
The same code, it works on both versions. I have tested.

**Comment by Bopske** [comment]
Strange: I tested too of course and it does not seem to have effect on a 2.0.15 install.

**Comment by dragomano** [comment]
Image 1
As you see the hint is on Russian (that used on my test forum). Check the Error log.

**Comment by Bopske** [comment]
never mind: it is working in 2.0.15. Thanks for the fix!

Just noticed that I had my test user set to log in in English... duh

**Pull request merged**
