### PR TITLE
Hide bars in Download section

### LINKED ISSUE #814: TPDownloads Upload Section shows blocks
The upload page/section in the download area has the blocks showing, this isn’t shown on category listings or others and they should be hidden.

### PR DESCRIPTION
**Pull request by tinoest**
Fixes #814

### CODE REVIEW

**Comment by Bopske** [comment]
This is hiding the bars when uploading a file only, right.?

I am not sure I would agree with that change. It is a matter of taste I guess...

**Comment by tinoest** [comment]
> This is hiding the bars when uploading a file only, right.?
> 
> I am not sure I would agree with that change. It is a matter of taste I guess...

Correct, it doesn’t look right to me. You can reject it if you’d like. As it is down to personal taste

**Comment by Bopske** [comment]
I tried to reject this PR tino, but I do not seem to have that option available anywhere. Can you do it?

**Comment by Bopske** [comment]
Nu reject option, but I can close them

**Pull request closed without merging**
