### PR TITLE
Fix for read more links in articles in 2.1

### PR DESCRIPTION
**Pull request by Bopske**
Not to be merged: needs testing

### CODE REVIEW

**Comment by Bopske** [comment]
That's the final fix. Now it can be merged.

**Comment by tinoest** [comment]
Doesn't this break wireless support? Not that I think many people use it now...

**Comment by Bopske** [comment]
I don't think so: I literally reused the php block syntax for the others as well: if it is broken now, php was already broken before. Tbh I considered removing the WIRELESS stuff completely: cannot think of anyone using WAP or WAP2 these days...

**Comment by TPMick** [comment]
Thought wireless was removed from 2.1 but I could be wrong.

**Comment by Bopske** [comment]
Yep it is, but our code was actually not written properly. Now it will only kick in if WIRELESS is available. So it is not in 2.1 and the code will be executed normally.

Let's merge this for now: removing Wireless completely may be an option for 2.0.0...

**Pull request merged**
