### PR TITLE
Removed remains sticky shouts

### PR DESCRIPTION
**Pull request by Bopske**

### CODE REVIEW

**Comment by Bopske** [comment]
First PR to development Branch to remove the remains of the sticky shouts. 
Two questions:
- is this ok this way?
- should we update the function updateShoutbox() in install.php to drop the redundant columns? If so, how?

**Comment by tinoest** [comment]
Looks ok to me, the remove the column if you look in the install.php for updateShoutbox there is a drop_column call.

**Comment by Bopske** [comment]
I think I made a mistake:  this PR is now pushing to 'master'? Is it not supposed to go to development? 

I just forked TP again and I now also have the development branch.. how does this merge now?

**Comment by tinoest** [comment]
> I think I made a mistake: this PR is now pushing to 'master'? Is it not supposed to go to development?
> 
> I just forked TP again and I now also have the development branch.. how does this merge now?

If you click edit you should be able to change it to development. If that doesn’t work, close the PR and create a new one from the base repo.

**Comment by Bopske** [comment]
Ok, changes are now in development branch and this PR contains the changes for a push to master. Not quite what I was expecting. Should I merge this PR with master or leave it open? I have tested the changes and the shoutbox works fine

**Comment by tinoest** [comment]
Leave it open and I’ll try and sort it later

**Comment by Bopske** [comment]
Thanks

**Review by tinoest — APPROVED** [review]

**Comment by tinoest** [comment]
Ohhh you did this directly on the TinyPortal/development branch not your own copy of it. 

Not quite what I had in mind but it's not an issue. 

That's why we can't merge to the TinyPortal/Development branch as it's already on there.

**Comment by Bopske** [comment]
Yeah had some issues getting the right branches and all. After all that I trashed my repository and forked TP again. Now I have all branches in my repository so I can work on the correct branch again. 

I think I am all set now to work on development . Just wondering when and how you plan to merge development back into master? Just before we release the next version? Or in between?

**Comment by tinoest** [comment]
> Yeah had some issues getting the right branches and all. After all that I trashed my repository and forked TP again. Now I have all branches in my repository so I can work on the correct branch again.
> 
> I think I am all set now to work on development . Just wondering when and how you plan to merge development back into master? Just before we release the next version? Or in between?

I think it makes sense when we are happy to release or just before? It means if there are any major issues with 2.0.0 we can fix those at our will and not have to worry about everything else being tested. I am open to your suggestions though.

**Comment by Bopske** [comment]
That sounds sensible to me. No problem. 
With the potential mess I created tonight I want to be careful: I do not know at this time how to merge branches so I do not want to create more issues.

**Comment by tinoest** [comment]
> That sounds sensible to me. No problem.
> With the potential mess I created tonight I want to be careful: I do not know at this time how to merge branches so I do not want to create more issues.

When you create the PR you should have a drop down to select which branch on TinyPortal repo to merge to. 

I can keep the master and development in sync with each other on the TinyPortal repo so we only commit any bug fixes to 2.0.0 (if they are applicable to it) and then I merge that with the development once we are happy.

**Comment by Bopske** [comment]
Deal!

**Comment by tinoest** [comment]
Closing as we don't want to merge development with master just yet.

**Pull request closed without merging**
