### PR TITLE
Correct spelling of attachment

### LINKED ISSUE #540: Avatar links in SMF2.0 not working in blocks
After installing latest 200 build on 2.0.17 the avatars in recent topics and other blocks are not showing.

In 1.6.5 the links are showing as follows:
https://test.fjr-club.nl/eigenavatars/avatar_691_1561454547.png

In 2.0.0 the links are formatted as:
https://test.fjr-club.nl/index.php?action=dlattach;attach=15187;type=avatar

... and resulting in broken images...

### PR DESCRIPTION
**Pull request by tinoest**
Might fix #540 can you please test @Bopske

### CODE REVIEW

**Comment by Bopske** [comment]
No change...

**Comment by tinoest** [comment]
Should fix #542 now

**Comment by Bopske** [comment]
Seems to be working with the new code. Thanks

**Comment by Bopske** [comment]
I think this cheange may be merged tino, I ll see if I can do some more testing for the other issues...

**Pull request merged**
