### PR TITLE
Removed Help page

### PR DESCRIPTION
**Pull request by Bopske**

### CODE REVIEW

**Comment by Bopske** [comment]
Tino,

I removed the old help pages from the code. I think I have it all but I found that the TpHelp files also contains the credits. Now it leaves some very small files in place.
I was thinking to move TPhelp.php into TPsubs.php.  TPhelp.template.php can go into TPsubs.template.php. Does that make sense to you?

**Comment by Bopske** [comment]
By the way: the sub action for the Tportal action is not escaped properly: if you now try to access the help sub action ( or any other non existing string) you get an error Unableto load the main template. Do you know how to prevent that ?

**Comment by tinoest** [comment]
It is escaped properly to my knowledge, if you try and access something which isn’t there it won’t load the main template as it doesn’t exist. 

I can throw an error and say the section doesn’t exist if you’d prefer. 

The whole idea behind mvc is multiple smaller files of similar code. Rather than one big file with varied code in it. 

I personally find most of the code sections to large and have been splitting them up logically. (Or I hope it’s logical)

**Comment by Bopske** [comment]
Any solution that does not put an error in the log is better. If we remove the Help sub-action many bots will still be hitting the page that does no longer exist causing many unneeded log entries.

You did not really answer my question: what do you think would be the logical place for the credits code? Leave it apart ? Or do you have a better idea?

**Comment by Bopske** [comment]
To prove my point: I removed the help on my test site yesterday and this morning I already have errors in the log from bots trying to index the page

**Comment by tinoest** [comment]
> To prove my point: I removed the help on my test site yesterday and this morning I already have errors in the log from bots trying to index the page

Well I can fix it, but it will break downloads, upshrink and many other things which don't use sa properly.

**Comment by Bopske** [comment]
That seems to create more problems than it solves . Perhaps just trigger the message if the sub action in ‘help’?

**Pull request merged**
