### PR TITLE
Updated profile to 2.1 format

### PR DESCRIPTION
**Pull request by Bopske**
Updated Shouts table to 2.1
Updated Articles tabel to 2.1

### CODE REVIEW

**Review by tinoest — COMMENTED** [review]
Can we not merge this until it’s tested as tables aren’t mobile friendly.

**Comment by tinoest** [comment]
What’s others thoughts on this? There was a lot of work done before I started helping TinyPortal on removing tables, I’m not against them but they’re not that friendly when going responsive.

**Comment by Bopske** [comment]
I know: I don't like the tables either. 
But if you check the code you'll see I left the responsiveness of the responsive divs in in TP place, just wrapped them in the Table format (tr only) used in Curve2, resulting in the 2.1 layout, while keeping the responsive behaviour of of TP. 

The shouts list is a full table, because the old one in TP was not responsive either. With only three columns it still behaves on narrow screens...

I tested this myself using mobile devices and narrow screens...

**Comment by Bopske** [comment]
Updated the TPshouts profile list to only use <tr>  in tables to keep complete responsive behaviour

**Comment by lurkalot** [comment]
Allvip tried hard to remove most of the tables when he first made TP responsive.  He got rid of a lot of them but other commitments got in the way.  I believe the ultimate goal was to get rid of them.  My understanding of this stuff is limited, and I don't even know if it's doable, but I do know it's a vast improvement on what we had.

**Comment by Bopske** [comment]
Sorry, I have used a table as does Smf curve2. The way I applied is is actually keeping everything Fully responsive AND in line with Curve layout for 2.1.

I only would use it in the profile area. For shouts articles and uploads.
This should be allowed as far as I am concerned .

**Comment by tinoest** [comment]
I’m happy enough with that. Let’s merge this. Can always change if it does cause issues.

I’d prefer a css grid or flex layout but I know IE 11 has issues with that and I can’t test them easily enough to sort it.

**Comment by Bopske** [comment]
Tnx

**Pull request merged**
