### PR TITLE
Added redirect for downloads, corrected version string to have a - in…

### PR DESCRIPTION
**Pull request by tinoest**
… the database

### CODE REVIEW

**Comment by Bopske** [comment]
Tino,

I just checked a number of dl links, the ones I expect to most commonly be used. The item links (first in the list) works. Other may need to be included too..

Link to a file:
https://test.fjr-club.nl/index.php?action=tpmod;dl=item3

Direct download link:
https://test.fjr-club.nl/index.php?action=tpmod;dl=get3

Link to category:
https://test.fjr-club.nl/index.php?action=tpmod;dl=cat2

Link to the upload link:
https://test.fjr-club.nl/index.php?action=tpmod;dl=upload

Link to search:
https://test.fjr-club.nl/index.php?action=tpmod;dl=search

Link to stats:
https://test.fjr-club.nl/index.php?action=tpmod;dl=stats

This preg replace stuff always confuses me, or I would have a go at it myself...

**Comment by tinoest** [comment]
^action=tpmod;dl=get([0-9]+)[\/]?$

Should be the next one, I started this then got distracted. I’ll try and look at it tomorrow or Wednesday.

**Comment by Bopske** [comment]
These are the first three...

        $paths = array (
            // Downloads
			'~^action=tpmod;dl=item([0-9]+)[\/]?$~'			            => '%1$s/index.php?action=tportal&sa=download;dl=item%2$s',
			'~^action=tpmod;dl=cat([0-9]+)[\/]?$~'			            => '%1$s/index.php?action=tportal&sa=download;dl=cat%2$s',
			'~^action=tpmod;dl=get([0-9]+)[\/]?$~'			            => '%1$s/index.php?action=tportal&sa=download;dl=get%2$s',
			);

**Comment by tinoest** [comment]
You should be able to add them to this pull request if you get to it before me, I’m on my phone can’t change easily.

**Comment by Bopske** [comment]
it should be simple to replace "action=tpmod;dl=" with "tportal&sa=download;dl=" but cannot get it to work

**Comment by Bopske** [comment]
Tino,  I think these three are the most important, and I have tested these: looks fine to me. Ill merge this one now...

**Pull request merged**
