### PR TITLE
shoutbox sorting and barposition

### PR DESCRIPTION
**Pull request by Bopske**
Adding two more shoutbox variables that control the barpositon as well as the shoutbox direction.
should address issue #939

There is one item I have not been able to fix yet: the ajax refresh still messes up the sort order and scrollbar position. Even with trying the solutions mentioned here...
https://www.simplemachines.org/community/index.php?msg=4138475

### CODE REVIEW

**Comment by tinoest** [comment]
@Bopske I was getting lost with all the variables so I stripped it out and went back to basics. 

https://github.com/tinoest/TinyPortal/tree/PR944

Can you review and let me know if you are happy with that method. I am not so happy with it being in the template but otherwise it seems to work correctly and I think is neater.

**Comment by Bopske** [comment]
Hi tino, I checked the changes and I agree with the approach: the number of places where the variables were to be maintained was getting very high, so this is cleaner.

I tested your version and it does have a few bugs though: the ajax refresh does not work anymore and I am getting some errors...

These:
https://localhost/vanilla/index.php?action=forum
 [C:/xampp/htdocs/vanilla/Sources/TPShout.php](https://localhost/vanilla/index.php?action=admin;area=logs;sa=errorlog;file=QzoveGFtcHAvaHRkb2NzL3ZhbmlsbGEvU291cmNlcy9UUFNob3V0LnBocA==;line=866) (Line 866)  [Backtrace information](https://localhost/vanilla/index.php?action=admin;area=logs;sa=errorlog;backtrace=27)

Type of error: Undefined
Error messageSelect
2: Undefined variable $set

and

https://localhost/vanilla/index.php?action=forum
 [C:/xampp/htdocs/vanilla/Sources/TPShout.php](https://localhost/vanilla/index.php?action=admin;area=logs;sa=errorlog;file=QzoveGFtcHAvaHRkb2NzL3ZhbmlsbGEvU291cmNlcy9UUFNob3V0LnBocA==;line=866) (Line 866)  [Backtrace information](https://localhost/vanilla/index.php?action=admin;area=logs;sa=errorlog;backtrace=28)

Type of error: General
Error messageSelect
2: Trying to access array offset on value of type null

**Comment by tinoest** [comment]
I’ll look at those tomorrow, it will be where I called one set and one data. Or an empty array as I hadn’t added the error checking.

**Comment by tinoest** [comment]
$("#tp_shout_'.$set['shoutbox_id'].'").keypress(function(event)

that should be row[‘id’] not set. Refresh not sure on

**Pull request closed without merging**
