### PR TITLE
Responsive updates

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Signed off by: Diego Andrés diegoandres_cortes@outlook.com

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
BTW I finally understood how GH works lol

**Comment by illori** [comment]
i will look at the changes but you have a greater chance of getting a merge if you add them to the SMF 2.1 branch of TP https://github.com/Tinyportal/TinyPortal-SMF2.1

**Comment by illori** [comment]
seems that we have a global a:hover that adds an underline... can we disable that for the blocks_toggle.\* classes? this is adding an underline under the toggles for the sidebars

**Comment by DiegoAndresCortes** [comment]
@illori I made several tests with the sidebars width and they always worked for me, at least in smf 2.0, can you explain how are they not working?
About the underline I will fix it

PS: Also I found another bug, didn't notice that the portal have the px by default, you can actually use percentage but it will remain the px in the width

**Comment by illori** [comment]
Have you looked at the sidebars on desktop view? Both should be the same
size. Left is smaller than right.

**Comment by DiegoAndresCortes** [comment]
Got it, I know from where it's coming that issue, will commit a fix.

**Comment by illori** [comment]
Great

**Comment by illori** [comment]
The sidebars are the same size but not the size they should be. About 175px
not 200.

**Comment by DiegoAndresCortes** [comment]
I have them working just fine, I can't reproduce this anymore

**Comment by illori** [comment]
Check the width with a px ruler they are not the correct size. Adjust size
in the admin panel.

**Comment by DiegoAndresCortes** [comment]
I compared it with another div box and the only difference is the padding betwen the sidebar and the center container

**Comment by illori** [comment]
Do you have the URL for lurkalot's testsite2? Compare the width of the
sidebars there and on tp.net. his site they are narrower.

**Comment by DiegoAndresCortes** [comment]
Can you link me there? I don't have the URL

**Comment by illori** [comment]
I sent it to you on tp.net

**Comment by lurkalot** [comment]
Just discovered that if I turn off the right panel, the left panel widens.

**Comment by lurkalot** [comment]
On that test site I have the left panel set to 250 and the right panel set at 220.  If I turn off the right panel the left panel widens to about 200

**Comment by DiegoAndresCortes** [comment]
Yeah I see it now. Something weird is happening when you enable both.
I'll try to fix it

**Comment by lurkalot** [comment]
Excellent, glad you spotted something. Thank you.

**Comment by DiegoAndresCortes** [comment]
Alright, it's done. Took me a while to solve a mobile issue so I ended up adding another class to the right sidebar and the ghost left sidebar.
Please test it

**Comment by lurkalot** [comment]
Thank you.  Unfortunately something's still not right, The left panel's overlapping the cennter blocks, and the right panel is bursting out the right hand side.  The actual panels look the right size now though.

**Comment by DiegoAndresCortes** [comment]
Can't reproduce that, not even in a brand new forum. I can't see anything you mentioned

**Comment by lurkalot** [comment]
Strange. I just tried in Xampp as well and it's the same as my test site. Does the test site look normal to you?

**Comment by DiegoAndresCortes** [comment]
Which test site?

**Comment by illori** [comment]
have you tested in firefox and internet explorer?

**Comment by lurkalot** [comment]
Tested in three different browsers.

It's this testsite http://cctestsite.info/testsite2/index.php

**Comment by illori** [comment]
in firefox, i can see some of the issues. i can see all the issues in IE on that test site.

**Comment by DiegoAndresCortes** [comment]
I just sorted out the normal style with three columns, left center right.
I haven't touched that column thing which I believe still using tables.

**Comment by lurkalot** [comment]
Diego, when you say you haven't touched that column thing, are you referring to the front page? It's in the forum where we're seeing the problems with the panels.  The front page looks ok to me.

**Comment by DiegoAndresCortes** [comment]
LOL I never checked the forum page

**Comment by lurkalot** [comment]
Still looks the same with that fix unfortunately. http://cctestsite.info/testsite2/index.php?action=forum

**Comment by lurkalot** [comment]
meant to say. The same in IE11 but in Firefox it looks good now. Getting closer. ;)

**Comment by lurkalot** [comment]
Tested in Firefox and Chrome, and Edge and it looks really good.  It's just IE11 that' it's not displaying properly..

**Comment by illori** [comment]
http://caniuse.com/#search=display%3Aflex if you look at the known issues tab, you will see a lot of ie issues, both in 10 and 11. i dont know if this can be worked around or corrected.

IE 11 does not vertically align items correctly when min-height is used see bug
In IE 10, setting -ms-flex-flow: row wrap will not wrap unless display: inline-block is set on child elements.
IE 11 incorrectly focuses a child element if the parent uses display:flex and has a tabindex set see testcase.
IE11 will not apply flexbox on pseudo-elements. See bug.
Flexbugs: community-curated list of flexbox issues and cross-browser workarounds for them
IE11 does not wrap long paragraphs of text
Firefox does not support Flexbox in button elements
In IE10 the default value for flex is 0 0 auto rather than 0 1 auto as defined in the latest spec.
In IE10 and IE11, containers with display: flex and flex-direction: column will not properly calculate their flexed childrens' sizes if the container has min-height but no explicit height property. See bug.

**Comment by illori** [comment]
@DiegoCortes any updates?

**Pull request closed without merging**
