### PR TITLE
php cs fixer

### PR DESCRIPTION
**Pull request by tinoest**
This create's a php standard which we can ensure all code complies with. 

We could use the config which is part of SMF 3 so we follow their standard explicitly. 

https://github.com/SimpleMachines/SMF/blob/release-3.0/.php-cs-fixer.dist.php

@Bopske @lurkalot before this is merged can you please check it as it's a lot of code changes!

Project is here - https://github.com/PHP-CS-Fixer/PHP-CS-Fixer

### CODE REVIEW

**Comment by Bopske** [comment]
How is this package supposed to be used? Is there an instruction?

**Comment by tinoest** [comment]
> How is this package supposed to be used? Is there an instruction?

It’s all on the project link. I use it with VSCode but you can run it on the command line.

**Comment by Bopske** [comment]
Just installed the latest code on my test forum. At first glance all seems to be working fine. 

Will give it some more tests this week and let you know if I find anything

**Comment by Bopske** [comment]
A did some tests and as far as I can see all works fine:
- tested articles and categories
- tested menu manager
- tested blocks
- tested downloads.

This can be merged, we'll see if anything comes up in beta testing

**Review by Bopske — APPROVED** [review]
Fine to merge

**Pull request merged**
