### PR TITLE
Fixes #417 

### PR DESCRIPTION
**Pull request by tinoest**
Can you please check this still works how you expect. I had to rewrite it a bit so it worked for both, but think I got all your changes correctly.

### CODE REVIEW

**Comment by Bopske** [comment]
Looks ok, best to test after the merge

**Review by Bopske — COMMENTED** [review]
Tino, I checked the updated code, and unfortunately your changes have broken the functionality completely.

The check for language in the query (line 311 and 316) in the previous code MUST be in that query to only pickup the blocks relevant for the language in TPBlock.php. 
Now blocks are always showing, regardless of the user language...

Same applies to the query in Tportal.php , line 1682, that deals with frontpanel blocks
' . (!empty($context['TPortal']['uselangoption']) ? 'AND FIND_IN_SET({string:lang}, access2)' : '') . '

Functionality is now non-functioning...

**Comment by tinoest** [comment]
Ok, I’ll look at it again. Your changes had broken PGSQL so we need to find the fix for both.

**Comment by Bopske** [comment]
Agreed, sorry about that. 
When fixing PGSQL the functionality should also remain working though...

FYI: the extra check in the query is actually limiting the selected blocks to only those that are set to show for the user language, so the AND clause can not be removed as such...

**Comment by tinoest** [comment]
I know we should maintain the fix. It seemed to on my testing, although I’m not sure if I got the configuration correct. 

It can’t remain, but it should be picked up the same in the query above I would of thought.

**Comment by Bopske** [comment]
Config for testing:
1. Set the general TP setting for Language visibility of blocks to ON
2. Create two blocks: set one to show for language 1 set the other to show for language 2
3. Toggle languages and check that the correct block is showing.

Test it both in the frontpanel (query in Tportal) and in another panel (query in TpBlock)

**Pull request merged**
