### PR TITLE
Added Standalone Mode

### PR DESCRIPTION
**Pull request by Rupurudu**
Added the TinyPortal Standalone Mode. 

- Fixed not working TPStandalone.php file, removed the unnecessary url rewrite function and Settings.php require. (SSI already handles that.)
- Added some logic to Integrate.php to properly handle Standalone mode. (Fix linktree and menu_buttons)
- Removed some code from the TPortal.php, which I believe is an older attempt of creating a standalone mode.
- Fully configurable Frontpage placement (Boardindex, Standalone, Disabled). This replaces the old "Go directly to forum index" option.

### CODE REVIEW

**Comment by tinoest** [comment]
Thanks, I’ll check this later. Although why have you changed the author when 90% of the file is what I provided? 

You should really add your name if you want credit as it’s bad etiquette to remove the original when it’s still largely their code.

The url rewrite was in as SSI.php changed the url for the links to the incorrect one when it was placed in a different subdomain, I’ll check and see if that’s still happening.

**Comment by Rupurudu** [comment]
> Thanks, I’ll check this later. Although why have you changed the author when 90% of the file is what I provided?
> 
> You should really add your name if you want credit as it’s bad etiquette to remove the original when it’s still largely their code.

I changed the header while changing the version string, all of the other files use version 3.0.1 while this one is left as 2.0.0. I could change it back, it wouldn't matter too much to me.

Also putting TPStandalone.php as the name didn't make sense, since user has to rename them to index.php and place it outside of the board directory. TinyPortal Standalone Mode is a better name.

> The url rewrite was in as SSI.php changed the url for the links to the incorrect one when it was placed in a different subdomain, I’ll check and see if that’s still happening.

Neither $boardurl, nor $scripturl should change other than the board default with this setup. (I tested this and it works.)

**Comment by Rupurudu** [comment]
@tinoest I changed the author back. 

Changed wrong $boarddir value detection.
Added translation settings for standalone mode.
Updated translation strings.

**Comment by tinoest** [comment]
> @tinoest I changed the author back.
> 
> Changed wrong $boarddir value detection. Added translation settings for standalone mode. Updated translation strings.

Thanks, you can add your name to the list. 

Did you sort the issue with the TinyPortal menu item not appearing? It's not showing on mine at the moment, just trying to work out if it's something else I have done.

I'm also not sure about adding the file to the board directory as standard, as how many people are going to know it's there or use it. I don't know where it should be if we don't though!

**Comment by Rupurudu** [comment]
> > @tinoest I changed the author back.
>
> Thanks, you can add your name to the list.

Should I put my name on a different line with a seperate @author line, or should I put it next to yours?

> Did you sort the issue with the TinyPortal menu item not appearing? It's not showing on mine at the moment, just trying to work out if it's something else I have done.

Yeah.
It's too late to call `TPortal_init();` in the TPStandalone.php, because `SSI.php` has already called `setupThemeContext()` before.
~~I'm going to move the `TPortal_init()` to the `integrate_SSI` hook.~~ Even this is too late.

> I'm also not sure about adding the file to the board directory as standard, as how many people are going to know it's there or use it. I don't know where it should be if we don't though!
It seemed like a good place to include it, I didn't want the board root and Forum parts point to the same place.

**Comment by Rupurudu** [comment]
Fixed the menu not showing up.

**Comment by tinoest** [comment]
> > > @tinoest I changed the author back.
> > 
> > 
> > Thanks, you can add your name to the list.
> 
> Should I put my name on a different line with a seperate @author line, or should I put it next to yours?
> 
Whichever you prefer. 

Let me know when you’ve finished the changes and I’ll get this merged the last lot seem to work well.

**Comment by tinoest** [comment]
@Rupurudu I've merged this and added you to the TPStandalone.php as an author. If this isn't ok let me know.

**Comment by Rupurudu** [comment]
It looks great! Thanks.

**Pull request merged**
