### PR TITLE
Update to TP shoutbox

### PR DESCRIPTION
**Pull request by Underdog-01**
- uses (newer) TP native JavaScript for DOM manipulation (better current/future control over SB behavior)
- fixed shoutbox form name/id to be unique (caused DOM conflict where multiple shoutboxes exist on 1 page)
- changed hyperlinks using empty hash anchor to inline divs (DOM doesn't need empty anchor links)
- tested on Firefox, Chrome, Safari, IE11, Edge (IE11 & Firefox now work correctly)

### CODE REVIEW

**Comment by Underdog-01** [comment]
I noticed that when one deletes a shout from the box itself it redirects to the admin section.
Is that the intended behavior? 
Shouldn't it be just an edit to that specific shout and then refresh the box but stay on the current page?
I can do this with a popup container or maybe even just a JS confirm box (<- I can make it appear & behave same as popup).
The latter is actually easier.

**Comment by Underdog-01** [comment]
I found one more thing to fix.
Expanding/Collapsing BBC & Smileys does not have unique id's and using it with multiple shoutboxes controls only one on the page where multiple shoutboxes exist.
I will add a fix for it in this PR shortly...

**Comment by Underdog-01** [comment]
Unique container id's are now being used

Please note that class & name do not have to be unique (unless it suits the the situation).
However, id's need to be unique where the container has the possibility of being used multiple times on one page.

There are going to be circumstances where people want ie. a shoutbox for admins and a shoutbox for regular members on one page.  

This needs to be thoroughly tested and run through a HTML validator prior to pushing it through (if that is the intent).
I will do these things over the next few days.

**Comment by Bopske** [comment]
Looking Good Underdog, I will give the code a proper testing. I just noticed a small typo somewhere, where you are referring to sNiley instead of a sMiley...

**Comment by Underdog-01** [comment]
Thanks.. it's been amended.

A small number of id's and/or classes in that specific file were not really necessary at this time including that one.
I added those in when I was changing id's to classes & prior to poking around in the other related files.
Most were necessary but some were not.
It can be left like that for future potential use. 

As I previously stated, the changes have been tested on multiple browsers and all seems in order.
These changes fix many HTML/JS-DOM errors that were directly related to the previous code. 

For the validator, I ignore the flagged empty span notations but try to fix everything else.
There is one misdemeanor warning left that I noticed but it is not related to the shoutbox.
It is from the TP menu popup.

**Pull request merged**
