### PR TITLE
Changes to support SMF 3.0

### PR DESCRIPTION
**Pull request by tinoest**
First round of changes to support SMF 3.0

### CODE REVIEW

**Comment by tinoest** [comment]
@Bopske This should still support SMF 2.1 without issue...

**Comment by Bopske** [comment]
I can test tomorrow if there are no issues with 2.1. I do not have a 3.0 test install yet ...

It is unfortunate : I just stripped out all the version checks when we dropped 2.0 support, and now they need to go for 3.0 support again...

**Comment by Bopske** [comment]
I just tested your changes on my SMF2.1 test forum: as far as I can see everything works fine. I cannot test this on 3.0 atm but I am okay with merging this in if you are: there is just a minor conflict with a style change I just merged...

**Comment by tinoest** [comment]
> I just tested your changes on my SMF2.1 test forum: as far as I can see everything works fine. I cannot test this on 3.0 atm but I am okay with merging this in if you are: there is just a minor conflict with a style change I just merged...

Happy for it to be merged, I can’t resolve the conflict atm as on mobile.

**Pull request merged**
