### PR TITLE
Fix for readmore showing even when full topic

### PR DESCRIPTION
**Pull request by Bopske**

### CODE REVIEW

**Comment by Bopske** [comment]
Tino, can you check this? This was how it was done before 2.0.0. Thing is that the new logic does not really cut strict at the maximum number of characters... so this may result in sometimes the Readmore text showing incorrectly. It would be better if we can check the result of shortenstring and see if anything is actually cut. 

Readmore shoul only be showing then....

**Comment by tinoest** [comment]
You don’t need $smcFunc it should be Util::strlen

ShortenString should return true or false if it does shorten it mind, that’s the better fix.

**Comment by Bopske** [comment]
"ShortenString should return true or false if it does shorten it mind, that’s the better fix."

I agree. But it does not do that yet, so I'll leave it up to you....

**Comment by tinoest** [comment]
> "ShortenString should return true or false if it does shorten it mind, that’s the better fix."
> 
> I agree. But it does not do that yet, so I'll leave it up to you....

Shall do, it’s Util::strlen btw that wraps around $smcFunc and also will allow it to work with Elkarte

**Pull request closed without merging**
