### PR TITLE
Updates for shoutbox and menu manager

### PR DESCRIPTION
**Pull request by Bopske**
- made classes tp specific to prevent issues with other shoutboxes
- increased icon sizes
- fix hover css for non-admins

### CODE REVIEW

**Comment by Bopske** [comment]
@tinoest I have made a series of updates to the shoutbox and the menu manager. Added a few features, therfore updated the next version ot 2.3.0 instead of 2.2.3.

I have one question for you, because I cannot find a small issue. 
I added a parameter to the shoutbox blocks to make the avatar optional in the layouts. Everything works fine, but for some reason I cannot get the selected option for 'show avatar' to show the selected option..



The code in question is in the template: TPBlockLayout.template.php

```
						<dt>'.$txt['tp-shoutboxavatar'].'</dt>
						<dd>
							<input type="radio" name="tp_block_var5" id="avataryes" value="1" ',$context['TPortal']['blockedit']['var5']=="1" ? 'checked="checked"' : '' ,' required /><label for="avataryes">'.$txt['tp-yes'].'</label>
							<input type="radio" name="tp_block_var5" id="avatarno" value="0" ',!$context['TPortal']['blockedit']['var5']=="1" ? 'checked="checked"' : '' ,' /><label for="avatarno">'.$txt['tp-no'].'</label>
						</dd>
```
It must be something really stupid, but I cannot find the reason that the active option does not get selected...

**Comment by Bopske** [comment]
One more minor inconvenience.

I added the extra parameter var5 to indicate the use of the avatar in the layout. Now when the shoutbox refreshes in the ajax call the parameter is lost and the avatars disappear. 

I know we had the same issue when I moved the shoutbox loayout to a block variable, but I cannot remember/find how we solved it.... need to do something similar for the 'shoutbox_avatar' variable like we did for the $shoutbox_layout variable

**Comment by tinoest** [comment]
@Bopske I’ll look at this properly at the weekend.

Personally I would just use a name saying what it is rather than var5, thought I’d removed those.

Yes you’ll have have to pass it through for it to be remembered. So it’ll need to be in the refresh url to remain persistent, or we create a session var which we check on load.

**Comment by Bopske** [comment]
Yeah, I tried to make that work by checking how you are dealing with the shoutbox layout, but I must be missing something. It's not working yet.. all my updates are in this PR. Did not want to merge it before it is working correctly...

**Comment by tinoest** [comment]
On an upgraded install I am getting this error; 

`2: Undefined array key "time_offset"`

[admin](http://127.0.0.1/index.php?action=profile;u=1)
[172.18.0.1](http://127.0.0.1/index.php?action=trackip;searchip=172.18.0.1)
[a62bad7b0abd40ea9e5a5e4eaa4e3542](http://127.0.0.1/index.php?action=admin;area=logs;sa=errorlog;desc;filter=session;value=a62bad7b0abd40ea9e5a5e4eaa4e3542)
http://127.0.0.1/index.php?
[/var/www/html/Themes/default/TPsubs.template.php](http://127.0.0.1/index.php?action=admin;area=logs;sa=errorlog;file=L3Zhci93d3cvaHRtbC9UaGVtZXMvZGVmYXVsdC9UUHN1YnMudGVtcGxhdGUucGhw;line=2606) (Line 2606)

**Comment by tinoest** [comment]
> @tinoest I have made a series of updates to the shoutbox and the menu manager. Added a few features, therfore updated the next version ot 2.3.0 instead of 2.2.3.
> 
> I have one question for you, because I cannot find a small issue. I added a parameter to the shoutbox blocks to make the avatar optional in the layouts. Everything works fine, but for some reason I cannot get the selected option for 'show avatar' to show the selected option..
> 
> 
> 
> The code in question is in the template: TPBlockLayout.template.php
> 
> ```
> 						<dt>'.$txt['tp-shoutboxavatar'].'</dt>
> 						<dd>
> 							<input type="radio" name="tp_block_var5" id="avataryes" value="1" ',$context['TPortal']['blockedit']['var5']=="1" ? 'checked="checked"' : '' ,' required /><label for="avataryes">'.$txt['tp-yes'].'</label>
> 							<input type="radio" name="tp_block_var5" id="avatarno" value="0" ',!$context['TPortal']['blockedit']['var5']=="1" ? 'checked="checked"' : '' ,' /><label for="avatarno">'.$txt['tp-no'].'</label>
> 						</dd>
> ```
> 
> It must be something really stupid, but I cannot find the reason that the active option does not get selected...

I can't work this one out, the html say's it should be checked.

**Comment by tinoest** [comment]
> 
> I can't work this one out, the html say's it should be checked.

@Bopske in the html at the end there is this line

`<input` type="radio" id="tp_block_var5" name="tp_block_var5" `value="99">`

That is causing the issue with the radio box, I don't know what that is there for.

**Comment by tinoest** [comment]
Screenshot 2022-10-21 at 17 44 36

Is it meant to look like this? That's layout 4 selected.

**Comment by Bopske** [comment]
Damn, just realized that we are already using the var5 field to store the block 'style' 
I am an idiot: should have seen that. The 99 default is for the setting to use the panel style.

So I cannot use the var5 variable to indicate the avatar use: The only way to do that would be by adding at least one variable to that array (var6?). Moght as well add a var 7 as well then to deal with the future requirements. 

What dou you think: is that feasible or will it require so much re-write that it is better left alone?

As for layout 4: that looks like it should be now when the avatars are activated

**Pull request closed without merging**
