### PR TITLE
Potentially fixes #409

### LINKED ISSUE #409: Block with single article in Frontpanel does not show the article body
See report here: https://www.tinyportal.net/index.php?topic=36334.msg297265#msg297265

I can reproduce it in both 2.0.15 and 2.1 RC2.
What I cannot yet figure out, is what exactly is missing: I have two articles that are identical in tp_articles (all settings the same) and one is showing, and one is not...

### PR DESCRIPTION
**Pull request by tinoest**

### CODE REVIEW

**Comment by tinoest** [comment]
@Bopske I think this fixes the issue you raised in #409 although I am not sure. The setting for showing on the front page wasn't being set when it was a frontpage article, I think that was the issue.

**Comment by Bopske** [comment]
I see you Made the fix in 2.0.0... I was working on this in 1.6.3...

**Comment by tinoest** [comment]
Sorry, my environment is set up for PGSQL so I couldn’t easily sort it in 1.6.4. 

I think it fixes the issue though. If you can’t test I’ll do the changes on 1.6.4 when I can.

**Comment by Bopske** [comment]
I just tried making the changes in 164 but it did not make a difference, also not after saving the articles again. Since your changes are not language related I doubt it this is the one...

**Comment by tinoest** [comment]
Ok, well it fixes a issue in 2.0.0 so I’ll commit it anyway. I’ll look at 1.6.3/4 next week when I get the chance.

**Comment by Bopske** [comment]
I did some tests on 2.0.0 and the articles in a block are not working at all. Not with your fix and it without. Regular blocks are fine but html and bbc articles in block are not being displayed at all.., not in any panel...

**Comment by Bopske** [comment]
I merged it in to do some more testing

**Pull request merged**
