### PR TITLE
Multiple Select Query 

### PR DESCRIPTION
**Pull request by tinoest**
@Bopske can you look into why the multiple select isn't showing correctly? If I add another select before it then it works fine. I just can't work out why it doesnt work in its current form and html is often beyond me.

### CODE REVIEW

**Comment by tinoest** [comment]
ignore me, was a browser cache issue

**Comment by Bopske** [comment]
Ha, I did not see the second comment til now: just checked the function and is working perfectly... this is the type of function we could use in more places...

**Comment by tinoest** [comment]
I needed a custom POST parser as the existing one in PHP overwrites the key hence that call and using php://input but I’ve done that in the past for other projects and it works fairly well.

**Comment by Bopske** [comment]
How easy is it to use this function elsewhere? I could use it in the include/exclude function as well...

**Comment by tinoest** [comment]
Relatively, it’s all in the last commit or two which you need. 

The implode is required later on but that’s usual.

**Comment by tinoest** [comment]
The only bit which was complex was the function to parse the _POST string.

**Pull request merged**
