### PR TITLE
Added length settings to recent topics

### PR DESCRIPTION
**Pull request by Bopske**

### CODE REVIEW

**Review by tinoest — CHANGES_REQUESTED** [review]
That changes the title, which you don’t want to do.

**Comment by Bopske** [comment]
What do you mean? We have had people asking about the length setting before. This allows the to do it themselves without code changes...

**Comment by tinoest** [comment]
> What do you mean? We have had people asking about the length setting before. This allows the to do it themselves without code changes...

title="' . $w['subject'] . '"

Which you’ve already shortened by this point… 

It should be a different variable you shorten then use that in place of shorten_subject.

**Comment by Bopske** [comment]
> > What do you mean? We have had people asking about the length setting before. This allows the to do it themselves without code changes...
> 
> title="' . $w['subject'] . '"
> 
> Which you’ve already shortened by this point…
> 
> It should be a different variable you shorten then use that in place of shorten_subject.

I see what you mean, and I saw that before, but I dod not really care that much, because it's simple title info and has no 'real' critical meaning, but indeed, it could be made better... I'll have a look

**Comment by tinoest** [comment]
@Bopske did you commit any changes? I can’t see any on GitHub since my last comment.

**Comment by Bopske** [comment]
Maybe I forgot to push them from my local repo will check tomorrow... done, its there now

**Pull request merged**
